name: Site Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-on-ubuntu:
    name: Run Python site tests on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements (none required)
        run: |
          python -V
      - name: Run Python site test
        run: |
          python tools/site_test.py index.html

  test-on-windows:
    name: Run PowerShell site tests on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PowerShell site test
        shell: pwsh
        run: |
          .\tools\site_test.ps1 -Path index.html
